//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



/** Auto-generated content model for Umbraco content type: Article builder (articleBuilderBlock) */
export interface UmbArticleBuilderBlock {
    blocks: UmbContentElementWithSettings[];
}

export enum UmbBackgroundPickerOption {
    Solid = "Solid",
    Transparent = "Transparent",
}

/** Auto-generated content model for Umbraco content type: Background styleable (backgroundStyleable) */
export interface UmbBackgroundStyleable {
    backgroundStyle: UmbBackgroundPickerOption;
}

/** Auto-generated content model for Umbraco content type: Background style (backgroundStyleSettings) */
export interface UmbBackgroundStyleSettings extends UmbBackgroundStyleable {
}

export interface UmbBreadcrumbItem {
    name: string;
    url: string;
}

/** Auto-generated content model for Umbraco content type: Bullet list (bulletListBlock) */
export interface UmbBulletListBlock {
    title: string | null;
    bulletPoints: string[];
}

/** Auto-generated content model for Umbraco content type: Image and text combination (combinationOneBlock) */
export interface UmbCombinationOneBlock {
    topImage: UmbMedia;
    topBlock: UmbContentElementWithSettings[];
    bottomMainBlocks: UmbContentElementWithSettings[];
    bottomSecondaryBlock: UmbContentElementWithSettings[];
}

/** Auto-generated content model for Umbraco content type: Themeable (themeable) */
export interface UmbThemeable {
    theme: string | null;
}

/** Auto-generated content model for Umbraco content type: Image and text combination (combinationOneSettings) */
export interface UmbCombinationOneSettings extends UmbThemeable {
    layout: UmbMirroredBlockLayoutOption;
}

/** Auto-generated content model for Umbraco content type: Video and text combination (combinationTwoBlock) */
export interface UmbCombinationTwoBlock {
    topMainBlock: UmbContentElementWithSettings[];
    topSecondaryBlock: UmbContentElementWithSettings[];
    bottomMainBlock: UmbContentElementWithSettings[];
    bottomSecondaryBlock: UmbContentElementWithSettings[];
}

/** Auto-generated content model for Umbraco content type: Video and text combination (combinationTwoSettings) */
export interface UmbCombinationTwoSettings extends UmbThemeable {
    layout: UmbMirroredBlockLayoutOption;
}

/** Auto-generated content model for Umbraco content type: Content spots (contentColumnsBlock) */
export interface UmbContentColumnsBlock {
    blocks: UmbContentElementWithSettings[];
}

export interface UmbContentElement {
    alias: string;
    content: any;
}

export interface UmbContentElementWithSettings extends UmbContentElement {
    settings: UmbContentElement | null;
}

/** Auto-generated content model for Umbraco content type: Content page (contentPage) */
export interface UmbContentPage {
    headerLead: string;
    headerTitle: string;
    headerText: string;
    headerImage: UmbMedia | null;
    navigationHide: boolean;
    headerTheme: string;
    contentBlocks: UmbContentElementWithSettings[];
}

export interface UmbCrop {
    alias: string;
    width: number;
    height: number;
    url: string;
}

export interface UmbFocalPoint {
    left: number;
    top: number;
}

/** Auto-generated content model for Umbraco content type: Home page (homePage) */
export interface UmbHomePage {
}

/** Auto-generated content model for Umbraco content type: Image and text (imageAndTextBlock) */
export interface UmbImageAndTextBlock {
    textBlock: UmbContentElementWithSettings[];
    mediaBlock: UmbContentElementWithSettings[];
}

/** Auto-generated content model for Umbraco content type: Image and text (imageAndTextSettings) */
export interface UmbImageAndTextSettings extends UmbThemeable {
    layout: UmbMirroredBlockLayoutOption;
}

/** Auto-generated content model for Umbraco content type: Image (imageBlock) */
export interface UmbImageBlock {
    image: UmbMedia;
}

export interface UmbImageCrop {
    url: string;
    focalPoint: UmbFocalPoint;
    crops: UmbCrop[];
}

/** Auto-generated content model for Umbraco content type: Image gallery item (imageGalleryItemBlock) */
export interface UmbImageGalleryItemBlock {
    image: UmbMedia;
    link: UmbNameAndUrl;
}

/** Auto-generated content model for Umbraco content type: Image gallery (imageGalleryOneBlock) */
export interface UmbImageGalleryOneBlock {
    images: UmbContentElementWithSettings[];
    block: UmbContentElementWithSettings[];
}

/** Auto-generated content model for Umbraco content type: Image gallery (imageGallerySettings) */
export interface UmbImageGallerySettings extends UmbThemeable {
    layout: UmbMirroredBlockLayoutOption;
}

/** Auto-generated content model for Umbraco content type: Image gallery (imageGalleryTwoBlock) */
export interface UmbImageGalleryTwoBlock {
    images: UmbContentElementWithSettings[];
    callToAction: UmbNameAndUrl;
}

/** Auto-generated content model for Umbraco content type: Image with call-to-action (imageWithCtaBlock) */
export interface UmbImageWithCtaBlock {
    image: UmbMedia;
    callToAction: UmbNameAndUrl | null;
}

/** Auto-generated content model for Umbraco content type: Landing page (landingPage) */
export interface UmbLandingPage {
    headerTopBlock: UmbContentElementWithSettings[];
    headerImage: UmbMedia;
    headerBottomBlock: UmbContentElementWithSettings[];
    headerTheme: string;
    headerNavigationTitle: string;
    headerNavigationTitleForChildren: string | null;
    contentBlocks: UmbContentElementWithSettings[];
}

export interface UmbLanguageAndUrl {
    language: string;
    url: string;
}

/** Auto-generated content model for Umbraco content type: Lead and title (leadAndTitle) */
export interface UmbLeadAndTitle {
    lead: string;
    title: string;
}

/** Auto-generated content model for Umbraco content type: Lead and title (leadAndTitleBlock) */
export interface UmbLeadAndTitleBlock extends UmbLeadAndTitle {
}

export interface UmbMedia extends UmbImageCrop {
    name: string;
    width: number;
    height: number;
    extension: string;
    additionalProperties: any;
}

export interface UmbMetadata {
    name: string;
    url: string;
    id: string;
    languages: UmbLanguageAndUrl[];
}

/** Auto-generated content model for Umbraco content type: Mini spot (miniBlock) */
export interface UmbMiniBlock {
    image: UmbMedia | null;
    block: UmbContentElementWithSettings[];
}

/** Auto-generated content model for Umbraco content type: Mini spots (miniBlocksBlock) */
export interface UmbMiniBlocksBlock {
    blocks: UmbContentElementWithSettings[];
}

export enum UmbMirroredBlockLayoutOption {
    Default = "Default",
    Mirrored = "Mirrored",
}

export interface UmbNameAndUrl {
    name: string;
    url: string;
}

export interface UmbNavigation {
    breadcrumb: UmbBreadcrumbItem[];
}

export interface UmbPageData {
    alias: string;
    content: any;
    metadata: UmbMetadata;
    navigation: UmbNavigation;
}

/** Auto-generated content model for Umbraco content type: Paragraph with call-to-action (paragraphWithCtaBlock) */
export interface UmbParagraphWithCtaBlock extends UmbLeadAndTitle {
    text: string;
    callToAction: UmbNameAndUrl | null;
}

/** Auto-generated content model for Umbraco content type: Paragraph With Image (paragraphWithImage) */
export interface UmbParagraphWithImage extends UmbParagraphWithCtaBlock {
    lead: string;
    title: string;
    image: UmbMedia | null;
}

/** Auto-generated content model for Umbraco content type: Product list (productListBlock) */
export interface UmbProductListBlock {
    title: string;
    productIds: string[];
}

/** Auto-generated content model for Umbraco content type: Product list with spot (productListWithContentBlock) */
export interface UmbProductListWithContentBlock {
    title: string;
    productIds: string[];
    block: UmbContentElementWithSettings[];
}

/** Auto-generated content model for Umbraco content type: Quote (quoteBlock) */
export interface UmbQuoteBlock {
    text: string;
    author: string;
    title: string;
}

/** Auto-generated content model for Umbraco content type: Quote With Image (quoteWithImage) */
export interface UmbQuoteWithImage extends UmbQuoteBlock {
    image: UmbMedia | null;
}

/** Auto-generated content model for Umbraco content type: Rich text (richTextBlock) */
export interface UmbRichTextBlock {
    text: string | null;
}

/** Auto-generated content model for Umbraco content type: Teaser spots (teaserColumnsBlock) */
export interface UmbTeaserColumnsBlock {
    blocks: UmbContentElementWithSettings[];
}

/** Auto-generated content model for Umbraco content type: Theme and background style (themeAndBackgroundStyleSettings) */
export interface UmbThemeAndBackgroundStyleSettings extends UmbBackgroundStyleable {
    theme: string | null;
}

/** Auto-generated content model for Umbraco content type: Theme (themeSettings) */
export interface UmbThemeSettings extends UmbThemeable {
}

/** Auto-generated content model for Umbraco content type: Video (videoBlock) */
export interface UmbVideoBlock {
    image: UmbMedia;
    title: string;
    video: UmbVideoUrlModel;
}

export enum UmbVideoSource {
    YouTube = "YouTube",
    Vimeo = "Vimeo",
}

export interface UmbVideoUrlModel {
    url: string;
    id: string;
    source: UmbVideoSource;
}

